/**
 * Loads the Ask Valluvar model and builds the classifier.
 *
 * The artifact is one small JSON file next to the corpus (`data/intents.json`,
 * generated by `npm run train:intent`), so the service worker precaches it with
 * everything else and Ask Valluvar works offline. Concurrent callers share one
 * request; a failure is not cached, so a later mount retries.
 */
import { createClassifier, type Classifier, type IntentModel } from './intentClassifier.ts'

const MODEL_URL = `${import.meta.env.BASE_URL}data/intents.json`

let promise: Promise<Classifier> | null = null

export function loadClassifier(): Promise<Classifier> {
  if (promise) return promise

  promise = (async () => {
    const response = await fetch(MODEL_URL, { credentials: 'same-origin' })
    if (!response.ok) throw new Error(`intents: request failed with ${response.status}`)
    const payload = (await response.json()) as IntentModel
    if (!Array.isArray(payload?.classes) || payload.classes.length === 0) throw new Error('intents: empty model')
    if (payload.hashBits !== 13) throw new Error('intents: model was built for a different feature space')
    return createClassifier(payload)
  })()

  promise.catch(() => {
    promise = null
  })

  return promise
}
